extends Node

# The sound bank. Every wav under assets/sfx is generated by tools/make_sfx.py
# -- the reasoning for synthesising them rather than checking in ten finished
# files is at the top of that script, along with what was wrong with the set it
# replaced. To change how anything in this game sounds, edit that file and run
# it; there is nothing to tune here.

var _streams := {}
var _players: Array[AudioStreamPlayer] = []

func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for sfx_name in ["tick", "coins", "jackpot", "attack", "raid", "shield", "error", "pop", "build", "levelup"]:
		var path := "res://assets/sfx/%s.wav" % sfx_name
		if ResourceLoader.exists(path):
			_streams[sfx_name] = load(path)
	# SIXTEEN, NOT TWELVE. `play` walks this list for a player that is not busy
	# and silently gives up if they all are, so the pool size is a ceiling on how
	# many of these can be audible at once. Twelve was sized against the old set,
	# where the longest sample was 450ms and most were under 200; the set built by
	# tools/make_sfx.py has a 1.45s fanfare and a 1.0s level-up with real tails on
	# them, so a player stays busy several times longer. A jackpot, a run of coin
	# landings and the taps underneath them now overlap in a way they could not
	# before -- and the sound that goes missing when the pool is full is always
	# the newest one, which is the one that just happened.
	for i in 16:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)

# `pitch` is the note the sample is played at; the jitter rides on top of it,
# so a caller that wants a rising run of the same sound sets the pitch per hit
# and still gets the small variation that stops repeats sounding mechanical.
func play(sfx_name: String, volume_db: float = 0.0, pitch_jitter: float = 0.06,
		pitch: float = 1.0) -> void:
	if not _streams.has(sfx_name):
		return
	for p in _players:
		if not p.playing:
			p.stream = _streams[sfx_name]
			p.volume_db = volume_db
			p.pitch_scale = pitch * randf_range(1.0 - pitch_jitter, 1.0 + pitch_jitter)
			p.play()
			return
