#!/usr/bin/env python3
"""Generate the bot-population migration from the game's own tables.

Loot Lagoon's rivals were nine NPCs invented on the device, which was fine while
raiding was theatre. Now that find_target answers from the server, the fallback
it falls back TO has to exist there -- and it has to look like a population
rather than a lineup, or the first thing a player notices is that the world is
small.

Two things are read out of scripts/cv.gd rather than restated here, because a
second copy is a copy that drifts:

  * BOT_DEFS -- the same names and faces the search screen already flickers
    through, so a rival the server hands back is one the player half recognises.
  * the economy curve -- 1.6^(level-1), snapped to three significant digits.
    A bot's vault has to be worth what a vault at its island is worth; a level 5
    bot holding a level 30 purse is the tell that there is no world out there.

Deterministic: same input, same migration, so re-running it produces no diff.

    tools/seed_bots.py > supabase/migrations/<stamp>_seed_bots.sql
"""

import random
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CV = ROOT / "scripts" / "cv.gd"

# Kept in step with cv.gd; asserted below rather than trusted.
ECONOMY_MAX_LEVEL = 30
ISLAND_COUNT = 30

PER_LEVEL = 4          # bots seeded at each island
BAND = 3               # find_target's default level band, ±3

SEED = 20260824        # any fixed number; this one is just the date


def read_bot_defs():
    text = CV.read_text()
    block = re.search(r"const BOT_DEFS\s*:=\s*\[(.*?)\n\]", text, re.S)
    if not block:
        sys.exit("could not find BOT_DEFS in cv.gd")
    defs = re.findall(r'\{"name":\s*"([^"]+)",\s*"emoji":\s*"([^"]+)"', block.group(1))
    if not defs:
        sys.exit("BOT_DEFS found but no entries parsed -- has its shape changed?")
    return defs


def curve(level):
    return 1.6 ** (min(max(level, 1), ECONOMY_MAX_LEVEL) - 1)


def scaled(base, level):
    """cv.gd's scaled(), reproduced exactly -- including the snap, because a
    vault that reads 1,246,151 next to payouts that read 1.25M looks wrong."""
    if base <= 0:
        return 0
    v = base * curve(level)
    step = 10.0
    while v / step >= 1000.0:
        step *= 10.0
    return int(round(v / step)) * int(step)


def main():
    defs = read_bot_defs()
    rng = random.Random(SEED)
    rows = []

    # A name may be reused on a distant island but never inside one band, so no
    # player ever sees the same face twice in a lineup. With BAND=3 a player can
    # see 2*BAND+1 levels at once, which is the window this has to keep clean.
    window = []   # [{name, ...}] for the last 2*BAND levels

    for level in range(1, ISLAND_COUNT + 1):
        recent = {n for lv in window[-(2 * BAND):] for n in lv}
        available = [d for d in defs if d[0] not in recent]
        if len(available) < PER_LEVEL:
            sys.exit(f"not enough distinct names for level {level}: "
                     f"{len(available)} free, need {PER_LEVEL}. "
                     f"Add names to BOT_DEFS or lower PER_LEVEL.")
        picked = rng.sample(available, PER_LEVEL)
        window.append([d[0] for d in picked])

        for name, emoji in picked:
            buildings = [rng.randint(1, 4) for _ in range(5)]
            # cv.gd's own purse, in island-1 units: mostly modest, one in six
            # loaded, which is what makes a search worth watching.
            purse = (rng.randint(9000, 16000) if rng.random() < 0.17
                     else rng.randint(1500, 6000))
            # Stored scaled, because the server compares it against real
            # players' vaults, and those are real figures.
            vault = scaled(purse, level)
            # A finished island is 75 stars (1+2+3+4+5 per hut, five huts), so
            # everything behind this one is a full island and this one is
            # whatever is standing. Keeps a bot's place on the leaderboard
            # consistent with the island it is standing on.
            rank = 75 * (level - 1) + sum(b * (b + 1) // 2 for b in buildings)
            shields = 1 if rng.random() < 0.35 else 0
            rows.append((name, emoji, level, rank, vault, shields, buildings))

    out = [f"""-- =============================================================================
--  A population for the raid net
-- =============================================================================
--
-- GENERATED by tools/seed_bots.py -- do not hand-edit; regenerate instead.
--
-- {len(rows)} bots, {PER_LEVEL} on each of {ISLAND_COUNT} islands, drawn from the same
-- BOT_DEFS faces the search screen already flickers through and priced on the
-- same 1.6x curve every other coin figure in the game uses. A level 5 bot
-- holding a level 30 purse is the tell that there is no world out there.
--
-- They are rows in `players` with is_bot = true, which is the whole trick:
-- find_target is one query, and "a human if there is one, a bot if there is
-- not" is one relaxed filter rather than a second code path that has to be
-- made indistinguishable by hand.
--
-- No name repeats inside a {2 * BAND + 1}-island window, so no player ever sees the same
-- face twice in one lineup.
--
-- Re-runnable: the delete clears the whole bot population first, so applying
-- this twice refreshes it rather than doubling it. The filter is is_bot, and
-- nothing else in the table carries that flag, so no real player is in reach --
-- bots have no identities and no save_blob.
--
-- It does cascade into `raids`, dropping the record of raids against the bots
-- being replaced. That is history about opponents that no longer exist, and no
-- real player's island is computed from it.
delete from public.players where is_bot = true;

insert into public.players
    (display_name, emoji, island_level, rank_stars, vault_coins, shields, buildings, is_bot, last_seen)
values"""]

    vals = []
    for name, emoji, level, rank, vault, shields, buildings in rows:
        b = "{" + ",".join(str(x) for x in buildings) + "}"
        vals.append(f"    ('{name}', '{emoji}', {level}, {rank}, {vault}, "
                    f"{shields}, '{b}', true, now())")
    out.append(",\n".join(vals) + ";")
    print("\n".join(out))


if __name__ == "__main__":
    main()
